<?php
/** @var Amasty\SecondModule\Block\Index $block*/
?>

<form method="post" action="http://localhost/magento2/alex/Sec/frm" data-mage-init='{"validation":{}}' class="<?= $block->getData('form_css') ?>">
    <p><b>Sku</b>
        <input type="text" name="sku">
    </p>
    <?php if ($block->isShowInput()) { ?>
        <p><b>Qrt</b>
            <input type="number" name="qty" value="<?= $block->getQRTNumber() ?>"   data-validate='{"required":true, "validate-not-negative-number":true}'>
           </p>
    <?php } ?>
    <div>
        <?= $block->getChildHtml() ?>
    </div>
    <input type="submit" value="Отправить">
</form>


